version: '3.3'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_ecommerce_g24
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5440:5432

  api:
    container_name: ecommerce.api
    build: .
    command: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
      - ./static:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: ecommerce.proxy
    build: ./nginx
    volumes:
      - ./app/static:/usr/src/app/static
    ports:
      - 8080:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume: